# Source: jxboot-helmfile-resources/templates/repositories.yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "dev"
  labels:
    jenkins.io/gitSync: "false"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  description: "the git repository for the Dev environment"
  provider: "https://github.com"
  providerName: 'github'
  org: "TueDissingWork"
  repo: "jenkins-jx3-minikube-vault"
  httpCloneURL: "https://github.com/TueDissingWork/jenkins-jx3-minikube-vault.git"
  url: "https://github.com/TueDissingWork/jenkins-jx3-minikube-vault.git"
  scheduler:
    kind: Scheduler
    name: "environment"
